Update CFloat32CustomPython.h
This is required in order to compile on Ubuntu 22.04.

Otherwise results in the following error:

astra-toolbox/build/linux/python/cython/./astra/CFloat32CustomPython.h:7:40: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘const PyArrayObject*’ {aka ‘const tagPyArrayObject_fields*’}